In [43]:
import pandas as pd
# Cargar el conjunto de datos dirtydata.csv
df = pd.read_csv("dirtydata.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0          1  '2020/12/01'    110       130     409.1
1          2  '2020/12/02'    117       145     479.0
2          3  '2020/12/03'    103       135     340.0
3          4  '2020/12/04'    109       175     282.4
4          5  '2020/12/05'    117       148     406.0
5          6  '2020/12/06'    102       127     300.0
6          7  '2020/12/07'    110       136     374.0
7          8  '2020/12/08'    104       134     253.3
8          9  '2020/12/09'    109       133     195.1
9         10  '2020/12/10'     98       124     269.0
10        11  '2020/12/11'    103       147     329.3
11        12  '2020/12/12'    100       120     250.7
12        13  '2020/12/12'    100       120     250.7
13        14  '2020/12/13'    106       128     345.3
14        15  '2020/12/14'    104       132     379.3
15        16  '2020/12/15'     98       123     275.0
16        17  '2020/12/16'     98       120     215.2
17        18  '2020/12/17'    100       120     300.0
18        19  '2020/12/18'     90       112       NaN
19        20  '2020/12/19'    103       123     323.0
20        21  '2020/12/20'     97       125     243.0
21        22  '2020/12/21'    108       131     364.2
22        23           NaN    100       119     282.0
23        24  '2020/12/23'    130       101     300.0
24        25  '2020/12/24'    105       132     246.0
25        26  '2020/12/25'    102       126     334.5
26        27      20201226    100       120     250.0
27        28  '2020/12/27'     92       118     241.0
28        29  '2020/12/28'    103       132       NaN
29        30  '2020/12/29'    100       132     280.0
30        31  '2020/12/30'    102       129     380.3
31        32  '2020/12/31'     92       115     243.0

In [44]:
# Mostrar los 5 primeros registros
print(df.head(5))

   Duration          Date  Pulse  Maxpulse  Calories
0         1  '2020/12/01'    110       130     409.1
1         2  '2020/12/02'    117       145     479.0
2         3  '2020/12/03'    103       135     340.0
3         4  '2020/12/04'    109       175     282.4
4         5  '2020/12/05'    117       148     406.0

In [45]:
# Mostrar la información del conjunto de datos
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
None

In [46]:
# Corregir el formato de la columna fecha
df['Date']=pd.to_datetime(df['Date'])
df

    Duration       Date  Pulse  Maxpulse  Calories
0          1 2020-12-01    110       130     409.1
1          2 2020-12-02    117       145     479.0
2          3 2020-12-03    103       135     340.0
3          4 2020-12-04    109       175     282.4
4          5 2020-12-05    117       148     406.0
5          6 2020-12-06    102       127     300.0
6          7 2020-12-07    110       136     374.0
7          8 2020-12-08    104       134     253.3
8          9 2020-12-09    109       133     195.1
9         10 2020-12-10     98       124     269.0
10        11 2020-12-11    103       147     329.3
11        12 2020-12-12    100       120     250.7
12        13 2020-12-12    100       120     250.7
13        14 2020-12-13    106       128     345.3
14        15 2020-12-14    104       132     379.3
15        16 2020-12-15     98       123     275.0
16        17 2020-12-16     98       120     215.2
17        18 2020-12-17    100       120     300.0
18        19 2020-12-18     90       112       NaN
19        20 2020-12-19    103       123     323.0
20        21 2020-12-20     97       125     243.0
21        22 2020-12-21    108       131     364.2
22        23        NaT    100       119     282.0
23        24 2020-12-23    130       101     300.0
24        25 2020-12-24    105       132     246.0
25        26 2020-12-25    102       126     334.5
26        27 2020-12-26    100       120     250.0
27        28 2020-12-27     92       118     241.0
28        29 2020-12-28    103       132       NaN
29        30 2020-12-29    100       132     280.0
30        31 2020-12-30    102       129     380.3
31        32 2020-12-31     92       115     243.0

In [47]:
# Remover celdas vacias o incorrectas
df = df.dropna()
df

    Duration       Date  Pulse  Maxpulse  Calories
0          1 2020-12-01    110       130     409.1
1          2 2020-12-02    117       145     479.0
2          3 2020-12-03    103       135     340.0
3          4 2020-12-04    109       175     282.4
4          5 2020-12-05    117       148     406.0
5          6 2020-12-06    102       127     300.0
6          7 2020-12-07    110       136     374.0
7          8 2020-12-08    104       134     253.3
8          9 2020-12-09    109       133     195.1
9         10 2020-12-10     98       124     269.0
10        11 2020-12-11    103       147     329.3
11        12 2020-12-12    100       120     250.7
12        13 2020-12-12    100       120     250.7
13        14 2020-12-13    106       128     345.3
14        15 2020-12-14    104       132     379.3
15        16 2020-12-15     98       123     275.0
16        17 2020-12-16     98       120     215.2
17        18 2020-12-17    100       120     300.0
19        20 2020-12-19    103       123     323.0
20        21 2020-12-20     97       125     243.0
21        22 2020-12-21    108       131     364.2
23        24 2020-12-23    130       101     300.0
24        25 2020-12-24    105       132     246.0
25        26 2020-12-25    102       126     334.5
26        27 2020-12-26    100       120     250.0
27        28 2020-12-27     92       118     241.0
29        30 2020-12-29    100       132     280.0
30        31 2020-12-30    102       129     380.3
31        32 2020-12-31     92       115     243.0